<?php
/**
 * Template Name: NamKhanh Landing Page v2
 * Generated by md_to_php.py v2 — Visual Interactive
 * Article: Trẻ Tự Kỷ Không Phản Ứng Khi Gọi Tên: Vì Sao Và Cách Hỗ Trợ
 */
get_header();
?>
<style>
:root{
  --p:#002795;--g:#FFD154;--t:#3D3D3D;--bg:#FAF9F6;
  --lt:#EEF1FB;--mid:#6B7280;--wh:#fff;
  --ok:#10B981;--warn:#F59E0B;--err:#E53E3E;
  --r:12px;--sh:0 4px 24px rgba(0,39,149,.12);
  --tr:.3s ease;--max:900px;
}
*,*::before,*::after{box-sizing:border-box;margin:0;padding:0}
body{font-family:'Segoe UI',system-ui,sans-serif;color:var(--t);background:var(--bg);line-height:1.7}
/* Progress bar */
#nkpb{position:fixed;top:0;left:0;height:3px;background:var(--g);width:0;z-index:9999;transition:width .1s linear}
/* Wrap */
.nk-wrap{max-width:var(--max);margin:0 auto;padding:0 20px}
/* Sections */
.nk-section{padding:64px 0}
.nk-section--flip{background:var(--lt)}
.nk-section--chain{background:var(--wh)}
.nk-section--compare{background:var(--lt)}
.nk-section--support{background:var(--wh)}
.nk-section--checklist{background:linear-gradient(135deg,#002795 0%,#0037c8 100%);color:var(--wh)}
.nk-section--faq{background:var(--bg)}
.nk-section--refs{background:var(--lt);font-size:.9rem}
.nk-sec-title{font-size:clamp(1.5rem,4vw,2rem);font-weight:800;margin-bottom:12px;color:var(--p)}
.nk-section--checklist .nk-sec-title{color:var(--g)}
.nk-sec-lead{color:var(--mid);margin-bottom:32px;font-size:1.05rem}
.nk-section--checklist .nk-sec-lead{color:rgba(255,255,255,.85)}
/* Hero */
.nk-hero{background:linear-gradient(135deg,#001a70 0%,var(--p) 60%,#0037c8 100%);color:var(--wh);padding:80px 0 60px;text-align:center}
.nk-hero__eye{display:inline-block;background:var(--g);color:var(--p);font-size:.75rem;font-weight:700;letter-spacing:1px;text-transform:uppercase;padding:4px 14px;border-radius:99px;margin-bottom:20px}
.nk-hero h1{font-size:clamp(1.8rem,5vw,2.8rem);font-weight:900;line-height:1.2;margin-bottom:20px;max-width:700px;margin-left:auto;margin-right:auto}
.nk-hero__lead{font-size:1.15rem;color:rgba(255,255,255,.87);max-width:600px;margin:0 auto 32px}
.nk-chips{display:flex;flex-wrap:wrap;gap:8px;justify-content:center;margin-top:8px}
.nk-chip{background:rgba(255,255,255,.15);border:1px solid rgba(255,255,255,.3);color:var(--wh);padding:4px 14px;border-radius:99px;font-size:.8rem}
/* Dots */
.nk-dots-wrap{text-align:center;padding:24px 0;background:var(--p)}
.nk-dots{display:flex;gap:8px;justify-content:center;margin-bottom:10px}
.nk-d{width:12px;height:12px;border-radius:50%;background:rgba(255,255,255,.3);display:inline-block}
.nk-d--on{background:var(--g);transform:scale(1.3)}
.nk-dots__txt{color:rgba(255,255,255,.8);font-size:.9rem}
/* Stat grid */
.nk-stat-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(200px,1fr));gap:24px;margin-top:32px}
.nk-stat{background:var(--wh);border-radius:var(--r);padding:32px 24px;text-align:center;box-shadow:var(--sh);border-top:4px solid var(--p)}
.nk-stat__icon{font-size:2rem;margin-bottom:12px}
.nk-stat__val{font-size:2.2rem;font-weight:900;color:var(--p);line-height:1}
.nk-stat__lbl{font-size:.85rem;color:var(--mid);margin-top:8px}
/* Flip cards */
.nk-flip-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(240px,1fr));gap:20px;perspective:1000px}
.nk-flip{height:180px;cursor:pointer;perspective:1000px}
.nk-fi{position:relative;width:100%;height:100%;transition:transform .5s;transform-style:preserve-3d}
.nk-flip.on .nk-fi{transform:rotateY(180deg)}
.nk-ff,.nk-fb{position:absolute;inset:0;border-radius:var(--r);padding:20px;backface-visibility:hidden;-webkit-backface-visibility:hidden}
.nk-ff{background:var(--wh);box-shadow:var(--sh);display:flex;flex-direction:column;justify-content:space-between}
.nk-fb{background:var(--p);color:var(--wh);transform:rotateY(180deg);display:flex;flex-direction:column;align-items:center;justify-content:center;text-align:center}
.nk-fc-num{font-size:1.5rem;font-weight:900;color:var(--p);opacity:.2}
.nk-ff p{font-size:.9rem;font-weight:600;flex:1;display:flex;align-items:center}
.nk-fc-hint{font-size:.75rem;color:var(--mid);text-align:right}
.nk-fb-ico{font-size:1.8rem;margin-bottom:10px}
.nk-fb p{font-size:.85rem;line-height:1.5}
/* Cause chain */
.nk-chain{display:flex;flex-direction:column;align-items:center;gap:0;margin-top:32px}
.nk-cs{display:flex;align-items:flex-start;gap:20px;background:var(--wh);border:2px solid var(--lt);border-radius:var(--r);padding:24px;max-width:640px;width:100%;box-shadow:var(--sh)}
.nk-chain-arrow{font-size:2rem;color:var(--p);text-align:center;line-height:1;padding:8px 0}
.nk-cs__icon{font-size:2rem;flex-shrink:0;width:52px;height:52px;background:var(--lt);border-radius:50%;display:flex;align-items:center;justify-content:center}
.nk-cs__title{font-size:1rem;font-weight:700;color:var(--p);margin-bottom:6px}
.nk-cs__desc{font-size:.9rem;color:var(--mid)}
/* Compare table */
.nk-cmp{overflow-x:auto;margin-top:32px;border-radius:var(--r);box-shadow:var(--sh)}
.nk-cmp table{width:100%;border-collapse:collapse;background:var(--wh)}
.nk-cmp th{background:var(--p);color:var(--wh);padding:16px 20px;text-align:left;font-size:.95rem}
.nk-cmp td{padding:14px 20px;border-bottom:1px solid var(--lt);font-size:.9rem;vertical-align:top}
.nk-cmp tr:last-child td{border-bottom:none}
.nk-cmp tr:nth-child(even) td{background:var(--lt)}
.nk-cmp__ok{color:var(--ok);font-weight:700;margin-right:6px}
.nk-cmp__warn{color:var(--warn);font-weight:700;margin-right:6px}
/* Support cards */
.nk-sc-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(250px,1fr));gap:24px;margin-top:32px}
.nk-sc{background:var(--lt);border-radius:var(--r);padding:28px;border-left:4px solid var(--p)}
.nk-sc__icon{font-size:2rem;margin-bottom:12px}
.nk-sc__title{font-size:1rem;font-weight:700;color:var(--p);margin-bottom:8px}
.nk-sc__desc{font-size:.875rem;color:var(--mid);margin-bottom:12px}
.nk-sc__list{padding-left:18px;font-size:.875rem}
.nk-sc__list li{margin-bottom:4px}
/* Checklist */
.nk-ck{max-width:620px;margin:0 auto}
.nk-ck__it{display:flex;align-items:flex-start;gap:14px;padding:14px 16px;margin-bottom:8px;background:rgba(255,255,255,.1);border-radius:10px;cursor:pointer;transition:background var(--tr)}
.nk-ck__it:hover{background:rgba(255,255,255,.2)}
.nk-ck__cb{position:absolute;opacity:0;width:0;height:0}
.nk-ck__box{flex-shrink:0;width:22px;height:22px;border:2px solid rgba(255,255,255,.5);border-radius:6px;display:flex;align-items:center;justify-content:center;transition:all var(--tr);margin-top:2px}
.nk-ck__cb:checked+.nk-ck__box{background:var(--g);border-color:var(--g);color:var(--p)}
.nk-ck__cb:checked+.nk-ck__box::after{content:'✓';font-weight:900;font-size:.85rem}
.nk-ck__txt{font-size:.95rem;line-height:1.5}
.nk-ck__result{margin-top:24px;text-align:center;padding:20px;border-radius:var(--r);background:rgba(255,255,255,.1)}
.nk-ck__counter{font-size:1.1rem;font-weight:700;margin-bottom:16px;color:var(--g)}
.nk-ck__msg{display:none;font-size:.95rem;padding:12px 18px;border-radius:8px;margin-top:8px}
.nk-ck__msg--lo.show{display:block;background:rgba(245,158,11,.2);border:1px solid var(--warn)}
.nk-ck__msg--mi.show{display:block;background:rgba(245,158,11,.3);border:1px solid var(--warn)}
.nk-ck__msg--hi.show{display:block;background:rgba(229,62,62,.25);border:1px solid var(--err)}
/* FAQ */
.nk-faq-wrap{max-width:700px;margin:32px auto 0}
.nk-fi2{border-bottom:1px solid var(--lt)}
.nk-fq{width:100%;text-align:left;background:none;border:none;padding:18px 0;font-size:1rem;font-weight:600;color:var(--t);cursor:pointer;display:flex;justify-content:space-between;align-items:center;gap:12px}
.nk-fq:hover{color:var(--p)}
.nk-fq__ic{font-size:1.4rem;font-weight:300;color:var(--p);flex-shrink:0;transition:transform var(--tr)}
.nk-fq[aria-expanded="true"] .nk-fq__ic{transform:rotate(45deg)}
.nk-fa{max-height:0;overflow:hidden;transition:max-height .4s ease}
.nk-fa p{padding:0 0 18px;color:var(--mid);font-size:.95rem}
/* CTA */
.nk-cta{background:var(--g);padding:64px 0;text-align:center}
.nk-cta h2{font-size:clamp(1.4rem,4vw,1.9rem);font-weight:900;color:var(--p);margin-bottom:12px}
.nk-cta p{color:var(--p);opacity:.8;margin-bottom:28px;font-size:1.05rem}
.nk-cta-btn{display:inline-block;background:var(--p);color:var(--wh);padding:16px 40px;border-radius:99px;font-weight:700;font-size:1.05rem;text-decoration:none;transition:transform var(--tr),box-shadow var(--tr)}
.nk-cta-btn:hover{transform:translateY(-2px);box-shadow:0 8px 24px rgba(0,39,149,.3)}
/* Disclaimer */
.nk-disc{background:#fffbeb;border-left:4px solid var(--warn);padding:16px 20px;margin:32px auto;max-width:var(--max);border-radius:0 var(--r) var(--r) 0;font-size:.875rem;color:var(--mid)}
/* Refs */
.nk-refs h3{font-size:1rem;font-weight:700;color:var(--p);margin:20px 0 10px}
.nk-refs ol,.nk-refs ul{padding-left:20px}
.nk-refs li{margin-bottom:6px;font-size:.85rem;color:var(--mid)}
/* Reveal animation */
.rev{opacity:0;transform:translateY(28px);transition:opacity .5s ease,transform .5s ease}
.rev.on{opacity:1;transform:none}
/* Responsive */
@media(max-width:600px){
  .nk-flip-grid{grid-template-columns:1fr 1fr}
  .nk-flip{height:160px}
  .nk-stat-grid{grid-template-columns:1fr}
  .nk-sc-grid{grid-template-columns:1fr}
  .nk-cs{flex-direction:column;gap:12px}
  .nk-cmp th,.nk-cmp td{padding:10px 12px;font-size:.8rem}
}
</style>
<div id="nkpb" role="progressbar" aria-label="Tiến độ đọc bài" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100"></div>

<main id="main" class="nk-main">

<div class="nk-hero">
  <div class="nk-wrap">
    <span class="nk-hero__eye">Nhóm triệu chứng 7/11</span>
    <h1>Trẻ Tự Kỷ Không Phản Ứng Khi Gọi Tên: Vì Sao Và Cách Hỗ Trợ</h1>
    <p class="nk-hero__lead">Trẻ tự kỷ không phản ứng khi gọi tên không phải do vấn đề thính giác. Hiểu nguyên nhân sinh học và tìm hướng hỗ trợ phù hợp cho con.</p>
    <div class="nk-chips"></div>
  </div>
</div>

<div class="nk-dots-wrap" aria-label="Tiến độ: nhóm 7 trong 11 nhóm triệu chứng">
  <div class="nk-dots">
    <span class="nk-d" aria-label="Nhóm 1" title="Nhóm 1"></span>
      <span class="nk-d" aria-label="Nhóm 2" title="Nhóm 2"></span>
      <span class="nk-d" aria-label="Nhóm 3" title="Nhóm 3"></span>
      <span class="nk-d" aria-label="Nhóm 4" title="Nhóm 4"></span>
      <span class="nk-d" aria-label="Nhóm 5" title="Nhóm 5"></span>
      <span class="nk-d" aria-label="Nhóm 6" title="Nhóm 6"></span>
      <span class="nk-d nk-d--on" aria-label="Nhóm 7" title="Nhóm 7"></span>
      <span class="nk-d" aria-label="Nhóm 8" title="Nhóm 8"></span>
      <span class="nk-d" aria-label="Nhóm 9" title="Nhóm 9"></span>
      <span class="nk-d" aria-label="Nhóm 10" title="Nhóm 10"></span>
      <span class="nk-d" aria-label="Nhóm 11" title="Nhóm 11"></span>
      
  </div>
  <p class="nk-dots__txt">Nhóm triệu chứng 7/11: <strong>Giao tiếp mắt</strong></p>
</div>

<section class="nk-section nk-section--stats" aria-labelledby="sec-stats">
  <div class="nk-wrap">
    <h2 id="sec-stats" class="nk-sec-title rev">Bằng Chứng Khoa Học</h2>
    <div class="nk-stat-grid">

    <div class="nk-stat rev">
      <div class="nk-stat__icon">🧠</div>
      <div class="nk-stat__val">8/11</div>
      <div class="nk-stat__lbl">nghiên cứu não bộ xác nhận</div>
    </div>
    <div class="nk-stat rev">
      <div class="nk-stat__icon">👁️</div>
      <div class="nk-stat__val">70%</div>
      <div class="nk-stat__lbl">thông tin cảm xúc truyền qua ánh mắt</div>
    </div>
    <div class="nk-stat rev">
      <div class="nk-stat__icon">👶</div>
      <div class="nk-stat__val">2–6 tháng</div>
      <div class="nk-stat__lbl">tuổi sớm nhất phát hiện dấu hiệu</div>
    </div>
    </div>
  </div>
</section>


<section class="nk-section nk-section--chain" aria-labelledby="sec-chain">
  <div class="nk-wrap">
    <h2 id="sec-chain" class="nk-sec-title rev">Nguyên Nhân Sinh Học</h2>
    <p class="nk-sec-lead rev">Chuỗi phản ứng trong não dẫn đến thiếu giao tiếp mắt:</p>
    <div class="nk-chain">

      <div class="nk-cs rev">
        <div class="nk-cs__icon">🔭</div>
        <div class="nk-cs__body">
          <h3 class="nk-cs__title">Não bộ chưa &quot;dán nhãn&quot; tên mình là tín hiệu ưu tiên</h3>
          <p class="nk-cs__desc">Với trẻ điển hình, tên của mình là một âm thanh đặc biệt. Từ khoảng 6–8 tháng tuổi, não bắt đầu nhận diện tên riêng như một tín hiệu xã hội quan trọng — một cái gì đó cần chú ý nga</p>
        </div>
      </div><div class="nk-chain-arrow" aria-hidden="true">↓</div>
      <div class="nk-cs rev">
        <div class="nk-cs__icon">⚡</div>
        <div class="nk-cs__body">
          <h3 class="nk-cs__title">Hệ thống phần thưởng xã hội hoạt động theo cách khác biệt</h3>
          <p class="nk-cs__desc">Một lý giải quan trọng đến từ trục oxytocin–dopamine trong não. Ở trẻ điển hình, tương tác xã hội — bao gồm việc ai đó gọi tên mình — kích hoạt vùng phần thưởng (nucleus accumbens </p>
        </div>
      </div><div class="nk-chain-arrow" aria-hidden="true">↓</div>
      <div class="nk-cs rev">
        <div class="nk-cs__icon">💧</div>
        <div class="nk-cs__body">
          <h3 class="nk-cs__title">Thiếu hụt định hướng xã hội (social orienting)</h3>
          <p class="nk-cs__desc">Trẻ tự kỷ không phản ứng khi gọi tên thường đi kèm với một khó khăn rộng hơn: chú ý chung (joint attention — khả năng chia sẻ sự tập trung với người khác về một đối tượng hay sự ki</p>
        </div>
      </div>
    </div>
  </div>
</section>

<section class="nk-section nk-section--compare" aria-labelledby="sec-cmp">
  <div class="nk-wrap">
    <h2 id="sec-cmp" class="nk-sec-title rev">Ảnh Hưởng Đến Phát Triển</h2>
    <div class="nk-cmp rev" role="table" aria-label="So sánh trẻ điển hình và trẻ tự kỷ">
      <table>
        <thead>
          <tr>
            <th scope="col">👧 Trẻ điển hình</th>
            <th scope="col">🧩 Trẻ có dấu hiệu tự kỷ</th>
          </tr>
        </thead>
        <tbody>

        <tr>
          <td><span class="nk-cmp__ok">✓</span> Trẻ điển hình nhìn mắt để bắt đầu giao tiếp</td>
          <td><span class="nk-cmp__warn">△</span> Phát triển ngôn ngữ: Phản ứng với tên là một trong những bước đầu tiên trong chuỗi học ngôn ngữ từ môi trường xung quanh. Khi không phản ứng tên, con bỏ lỡ rất nhiều cơ hội học ngôn ngữ tự nhiên mỗi ngày.</td>
        </tr>
        <tr>
          <td><span class="nk-cmp__ok">✓</span> Biểu cảm khuôn mặt được đọc tự nhiên</td>
          <td><span class="nk-cmp__warn">△</span> Chú ý chung và học qua quan sát: Không phản ứng tên đồng nghĩa với ít khởi xướng chú ý chung hơn. Mà chú ý chung lại là nền tảng để học qua quan sát — cách trẻ học phần lớn kỹ năng xã hội và ngôn ngữ trong những năm đầu đời.</td>
        </tr>
        <tr>
          <td><span class="nk-cmp__ok">✓</span> Kết nối cảm xúc qua ánh mắt hình thành tự động</td>
          <td><span class="nk-cmp__warn">△</span> Vòng lặp tương tác xã hội: Mỗi lần trẻ phản ứng khi được gọi tên là một &quot;vòng lặp xã hội&quot; — cha mẹ gọi, con phản ứng, cha mẹ tiếp tục tương tác. Trẻ điển hình có hàng chục đến hàng trăm vòng lặp như vậy mỗi ngày. Trẻ không phản ứng tên mất đi phần lớn những vòng lặp này.</td>
        </tr>
        <tr>
          <td><span class="nk-cmp__ok">✓</span> Trẻ tìm kiếm ánh mắt cha mẹ để học hỏi</td>
          <td><span class="nk-cmp__warn">△</span> </td>
        </tr>
        </tbody>
      </table>
    </div>
  </div>
</section>

<section class="nk-section nk-section--support" aria-labelledby="sec-sup">
  <div class="nk-wrap">
    <h2 id="sec-sup" class="nk-sec-title rev">Hướng Hỗ Trợ Hiệu Quả</h2>
    <div class="nk-sc-grid">

    <div class="nk-sc rev">
      <div class="nk-sc__icon">🎯</div>
      <h3 class="nk-sc__title">Can thiệp hành vi (ABA)</h3>
      <p class="nk-sc__desc">ABA (Phân tích hành vi ứng dụng) hiện là phương pháp có bằng chứng mạnh nhất trong việc xây dựng phản ứng với tên ở trẻ </p>
      
    </div>
    <div class="nk-sc rev">
      <div class="nk-sc__icon">🗣️</div>
      <h3 class="nk-sc__title">Floortime / DIR</h3>
      <p class="nk-sc__desc">Floortime (Trị liệu sàn nhà) tiếp cận theo hướng xây dựng động lực xã hội từ bên trong: cha mẹ tham gia vào thế giới của</p>
      
    </div>
    <div class="nk-sc rev">
      <div class="nk-sc__icon">🏠</div>
      <h3 class="nk-sc__title">Những điều cha mẹ có thể làm</h3>
      
      <ul class="nk-sc__list"><li>Gọi tên ở khoảng cách gần, ngang tầm mắt — không phải gọi từ xa hay từ phía sau lưng. Khoảng cách 30–60cm và ngang tầm mắt giúp não của con dễ liên kết âm thanh với khuôn mặt quen thuộc hơn.</li><li>Gọi tên một lần, rồi chờ — gọi đi gọi lại liên tục có thể làm tên trở thành &quot;nhiễu&quot; nền. Gọi một lần, chờ 3–5 giây, hỗ trợ nhẹ nếu cần, sau đó khen ngợi ngay khi con quay lại.</li><li>Kết nối tên với phần thưởng ngay lập tức — khi con phản ứng với tên, dù chỉ thoáng, hãy phản ứng ngay bằng thứ con thích. Não học qua liên kết lặp lại.</li><li>Giảm &quot;nhiễu&quot; kích thích cạnh tranh — tắt màn hình, TV khi muốn luyện tập gọi tên. Khi có quá nhiều kích thích cạnh tranh, não trẻ tự kỷ càng khó ưu tiên tín hiệu xã hội.</li></ul>
    </div>
    </div>
  </div>
</section>

<section class="nk-section nk-section--checklist" aria-labelledby="sec-ck">
  <div class="nk-wrap">
    <h2 id="sec-ck" class="nk-sec-title rev">Checklist Nhận Diện Nhanh</h2>
    <p class="nk-sec-lead rev">Tick vào những dấu hiệu bạn nhận thấy ở con:</p>
    <div class="nk-ck rev" role="group" aria-labelledby="sec-ck">

      <label class="nk-ck__it" for="ck0">
        <input type="checkbox" id="ck0" class="nk-ck__cb">
        <span class="nk-ck__box" aria-hidden="true"></span>
        <span class="nk-ck__txt">Trước 6 tháng: Không phản ứng với âm thanh xã hội là bình thường — hệ thần kinh chưa phát triển đủ để xử lý tín hiệu xã hội phức tạp.</span>
      </label>
      <label class="nk-ck__it" for="ck1">
        <input type="checkbox" id="ck1" class="nk-ck__cb">
        <span class="nk-ck__box" aria-hidden="true"></span>
        <span class="nk-ck__txt">6–9 tháng: Trẻ điển hình bắt đầu nhận ra và quay về phía tiếng gọi tên.</span>
      </label>
      <label class="nk-ck__it" for="ck2">
        <input type="checkbox" id="ck2" class="nk-ck__cb">
        <span class="nk-ck__box" aria-hidden="true"></span>
        <span class="nk-ck__txt">9–12 tháng: Không phản ứng nhất quán với tên riêng — cần theo dõi và ghi chép cụ thể.</span>
      </label>
      <label class="nk-ck__it" for="ck3">
        <input type="checkbox" id="ck3" class="nk-ck__cb">
        <span class="nk-ck__box" aria-hidden="true"></span>
        <span class="nk-ck__txt">12–18 tháng: Không phản ứng ổn định trong nhiều hoàn cảnh, nhiều người gọi — nên tham khảo ý kiến bác sĩ nhi khoa để được đánh giá.</span>
      </label>
      <label class="nk-ck__it" for="ck4">
        <input type="checkbox" id="ck4" class="nk-ck__cb">
        <span class="nk-ck__box" aria-hidden="true"></span>
        <span class="nk-ck__txt">18–24 tháng: Không phản ứng tên đi kèm với các triệu chứng khác (ít giao tiếp mắt, chưa nói, ít chơi tương tác) — cần đánh giá chuyên sâu.</span>
      </label>
      <div class="nk-ck__result" aria-live="polite" aria-atomic="true">
        <div class="nk-ck__counter">Đã chọn: <strong id="nkCkCount">0</strong>/5 dấu hiệu</div>
        <div class="nk-ck__msg nk-ck__msg--lo" id="nkMsgLo">
          <span>🟡</span> Quan sát thêm. Một vài dấu hiệu có thể do nhiều nguyên nhân.
        </div>
        <div class="nk-ck__msg nk-ck__msg--mi" id="nkMsgMi">
          <span>🟠</span> Đáng chú ý. Nên theo dõi và tham khảo chuyên gia.
        </div>
        <div class="nk-ck__msg nk-ck__msg--hi" id="nkMsgHi">
          <span>🔴</span> Nhiều dấu hiệu rõ rệt. Khuyến nghị đánh giá chuyên sâu sớm.
        </div>
      </div>
    </div>
  </div>
</section>

<section class="nk-section nk-section--faq" aria-labelledby="sec-faq">
  <div class="nk-wrap">
    <h2 id="sec-faq" class="nk-sec-title rev">Câu Hỏi Thường Gặp</h2>
    <div class="nk-faq-wrap">

    <div class="nk-fi2">
      <button class="nk-fq" id="fq0" aria-expanded="false" aria-controls="fa0">
        <span>Con tôi không quay khi gọi tên. Có chắc chắn là tự kỷ không?</span>
        <span class="nk-fq__ic" aria-hidden="true">+</span>
      </button>
      <div class="nk-fa" id="fa0" role="region" aria-labelledby="fq0">
        <p>Không phản ứng khi gọi tên là một dấu hiệu cần theo dõi, không phải chẩn đoán. Nhiều nguyên nhân khác có thể gây ra tình trạng này: khiếm thính nhẹ, chậm phát triển ngôn ngữ, hoặc đơn giản là giai đoạn phát triển bình thường ở một số trẻ. Nếu triệu chứng kéo dài và nhất quán sau 12 tháng, hãy thảo luận với bác sĩ nhi khoa để được đánh giá đầy đủ hơn.</p>
      </div>
    </div>
    <div class="nk-fi2">
      <button class="nk-fq" id="fq1" aria-expanded="false" aria-controls="fa1">
        <span>Tại sao con không nghe tên nhưng lại nghe nhạc quảng cáo rõ mồn một?</span>
        <span class="nk-fq__ic" aria-hidden="true">+</span>
      </button>
      <div class="nk-fa" id="fa1" role="region" aria-labelledby="fq1">
        <p>Đây là câu hỏi mà rất nhiều cha mẹ đặt ra. Não của trẻ tự kỷ có xu hướng xử lý âm thanh không xã hội (nhạc, âm thanh máy móc) tốt hơn âm thanh xã hội (giọng người, tên riêng). Hai loại âm thanh này được xử lý qua các đường thần kinh khác nhau — và đường xử lý âm thanh không xã hội thường không bị ảnh hưởng theo cùng cách.</p>
      </div>
    </div>
    <div class="nk-fi2">
      <button class="nk-fq" id="fq2" aria-expanded="false" aria-controls="fa2">
        <span>Con bao nhiêu tuổi thì bắt đầu can thiệp?</span>
        <span class="nk-fq__ic" aria-hidden="true">+</span>
      </button>
      <div class="nk-fa" id="fa2" role="region" aria-labelledby="fq2">
        <p>Càng sớm càng tốt. Nghiên cứu nhất quán chỉ ra rằng can thiệp bắt đầu trước 3 tuổi cho kết quả tốt hơn đáng kể. Tuy nhiên, can thiệp ở bất kỳ độ tuổi nào cũng đều có giá trị — não bộ con người có khả năng thích nghi (neuroplasticity) đáng kể.</p>
      </div>
    </div>
    <div class="nk-fi2">
      <button class="nk-fq" id="fq3" aria-expanded="false" aria-controls="fa3">
        <span>Nếu con phản ứng tên ở nhà nhưng không phản ứng ở nơi khác?</span>
        <span class="nk-fq__ic" aria-hidden="true">+</span>
      </button>
      <div class="nk-fa" id="fa3" role="region" aria-labelledby="fq3">
        <p>Đây là hiện tượng rất phổ biến gọi là &quot;khó khái quát hóa&quot; (generalization deficit). Con đã học được phản xạ trong bối cảnh quen thuộc, nhưng chưa chuyển được kỹ năng đó sang môi trường mới. Đây là lý do tại sao các chương trình can thiệp chú trọng đến việc luyện tập trong nhiều bối cảnh, nhiều người khác nhau.</p>
      </div>
    </div>
    <div class="nk-fi2">
      <button class="nk-fq" id="fq4" aria-expanded="false" aria-controls="fa4">
        <span>Việc luyện tập gọi tên ở nhà có ích không nếu chưa có chuyên gia?</span>
        <span class="nk-fq__ic" aria-hidden="true">+</span>
      </button>
      <div class="nk-fa" id="fa4" role="region" aria-labelledby="fq4">
        <p>Có, và rất quan trọng — nhưng cần làm đúng cách. Gọi tên quá nhiều mà không có phản ứng dương tính khi con quay lại có thể làm tên trở thành âm thanh &quot;nền&quot; vô nghĩa. Nguyên tắc: gọi ít hơn nhưng mỗi lần có phản ứng của con (dù nhỏ) đều được nhận ra và khen ngay.</p>
      </div>
    </div>
    <div class="nk-fi2">
      <button class="nk-fq" id="fq5" aria-expanded="false" aria-controls="fa5">
        <span>Trẻ bao lâu thì bắt đầu phản ứng tên sau khi được can thiệp?</span>
        <span class="nk-fq__ic" aria-hidden="true">+</span>
      </button>
      <div class="nk-fa" id="fa5" role="region" aria-labelledby="fq5">
        <p>Thời gian thay đổi đáng kể tùy theo mức độ khó khăn và cường độ luyện tập. Một số trẻ phản ứng cải thiện sau vài tuần luyện tập nhất quán; một số khác cần nhiều tháng. Nghiên cứu cho thấy kết quả tốt nhất khi can thiệp được duy trì đủ cường độ và kéo dài từ 12 tháng trở lên.</p>
      </div>
    </div>
    </div>
  </div>
</section>

<section class="nk-cta" aria-labelledby="sec-cta">
  <div class="nk-wrap">
    <h2 id="sec-cta">Bước Tiếp Theo Cho Bé</h2>
    <p>Đội ngũ chuyên gia sẵn sàng hỗ trợ bạn.</p>
    <a href="https://npfood.edu.vn" class="nk-cta-btn" role="button">Nhận Tư Vấn Miễn Phí</a>
  </div>
</section>

<div class="nk-dots-wrap" aria-label="Tiến độ: nhóm 7 trong 11 nhóm triệu chứng">
  <div class="nk-dots">
    <span class="nk-d" aria-label="Nhóm 1" title="Nhóm 1"></span>
      <span class="nk-d" aria-label="Nhóm 2" title="Nhóm 2"></span>
      <span class="nk-d" aria-label="Nhóm 3" title="Nhóm 3"></span>
      <span class="nk-d" aria-label="Nhóm 4" title="Nhóm 4"></span>
      <span class="nk-d" aria-label="Nhóm 5" title="Nhóm 5"></span>
      <span class="nk-d" aria-label="Nhóm 6" title="Nhóm 6"></span>
      <span class="nk-d nk-d--on" aria-label="Nhóm 7" title="Nhóm 7"></span>
      <span class="nk-d" aria-label="Nhóm 8" title="Nhóm 8"></span>
      <span class="nk-d" aria-label="Nhóm 9" title="Nhóm 9"></span>
      <span class="nk-d" aria-label="Nhóm 10" title="Nhóm 10"></span>
      <span class="nk-d" aria-label="Nhóm 11" title="Nhóm 11"></span>
      
  </div>
  <p class="nk-dots__txt">Nhóm triệu chứng 7/11: <strong>Giao tiếp mắt</strong></p>
</div>


</main>

<script>
(function(){
  // 1. Reading progress bar
  var pb=document.getElementById('nkpb');
  function updPb(){
    var sc=document.documentElement.scrollTop||document.body.scrollTop;
    var h=document.documentElement.scrollHeight-document.documentElement.clientHeight;
    if(pb) pb.style.width=(h>0?Math.round(sc/h*100):0)+'%';
  }
  window.addEventListener('scroll',updPb,{passive:true});

  // 2. Scroll reveal (IntersectionObserver)
  var ro=new IntersectionObserver(function(entries){
    entries.forEach(function(e){
      if(e.isIntersecting){e.target.classList.add('on');ro.unobserve(e.target);}
    });
  },{threshold:.12,rootMargin:'0px 0px -40px 0px'});
  document.querySelectorAll('.rev').forEach(function(el){ro.observe(el);});

  // 3. Flip cards
  document.querySelectorAll('.nk-flip').forEach(function(card){
    function toggle(){
      var on=card.classList.toggle('on');
      card.setAttribute('aria-pressed',on?'true':'false');
    }
    card.addEventListener('click',toggle);
    card.addEventListener('keydown',function(e){
      if(e.key==='Enter'||e.key===' '){e.preventDefault();toggle();}
    });
  });

  // 4. FAQ accordion
  document.querySelectorAll('.nk-fq').forEach(function(btn){
    btn.addEventListener('click',function(){
      var exp=this.getAttribute('aria-expanded')==='true';
      // close all
      document.querySelectorAll('.nk-fq').forEach(function(b){
        b.setAttribute('aria-expanded','false');
        var ans=document.getElementById(b.getAttribute('aria-controls'));
        if(ans) ans.style.maxHeight='0';
      });
      if(!exp){
        this.setAttribute('aria-expanded','true');
        var ans=document.getElementById(this.getAttribute('aria-controls'));
        if(ans) ans.style.maxHeight=ans.scrollHeight+'px';
      }
    });
  });

  // 5. Checklist counter
  var cbs=document.querySelectorAll('.nk-ck__cb');
  var countEl=document.getElementById('nkCkCount');
  var msgLo=document.getElementById('nkMsgLo');
  var msgMi=document.getElementById('nkMsgMi');
  var msgHi=document.getElementById('nkMsgHi');
  function updCk(){
    var n=document.querySelectorAll('.nk-ck__cb:checked').length;
    if(countEl) countEl.textContent=n;
    if(msgLo) msgLo.classList.toggle('show',n>=1&&n<=2);
    if(msgMi) msgMi.classList.toggle('show',n>=3&&n<=4);
    if(msgHi) msgHi.classList.toggle('show',n>=5);
  }
  cbs.forEach(function(cb){cb.addEventListener('change',updCk);});
})();
</script>

<script type="application/ld+json">
{
  "@context": "https://schema.org",
  "@graph": [
    {
      "@type": "Article",
      "headline": "Trẻ Tự Kỷ Không Phản Ứng Khi Gọi Tên: Vì Sao Và Cách Hỗ Trợ",
      "description": "Trẻ tự kỷ không phản ứng khi gọi tên không phải do vấn đề thính giác. Hiểu nguyên nhân sinh học và tìm hướng hỗ trợ phù hợp cho con.",
      "url": "https://npfood.edu.vn/tr-t-k-khong-ph-n-ung-khi-goi-ten-vi-sao",
      "author": {
        "@type": "Organization",
        "name": "Nam Khánh"
      },
      "publisher": {
        "@type": "Organization",
        "name": "Nam Khánh",
        "url": "https://npfood.edu.vn"
      }
    },
    {
      "@type": "FAQPage",
      "mainEntity": [
        {
          "@type": "Question",
          "name": "Con tôi không quay khi gọi tên. Có chắc chắn là tự kỷ không?",
          "acceptedAnswer": {
            "@type": "Answer",
            "text": "Không phản ứng khi gọi tên là một dấu hiệu cần theo dõi, không phải chẩn đoán. Nhiều nguyên nhân khác có thể gây ra tình trạng này: khiếm thính nhẹ, chậm phát triển ngôn ngữ, hoặc đơn giản là giai đoạn phát triển bình thường ở một số trẻ. Nếu triệu chứng kéo dài và nhất quán sau 12 tháng, hãy thảo luận với bác sĩ nhi khoa để được đánh giá đầy đủ hơn."
          }
        },
        {
          "@type": "Question",
          "name": "Tại sao con không nghe tên nhưng lại nghe nhạc quảng cáo rõ mồn một?",
          "acceptedAnswer": {
            "@type": "Answer",
            "text": "Đây là câu hỏi mà rất nhiều cha mẹ đặt ra. Não của trẻ tự kỷ có xu hướng xử lý âm thanh không xã hội (nhạc, âm thanh máy móc) tốt hơn âm thanh xã hội (giọng người, tên riêng). Hai loại âm thanh này được xử lý qua các đường thần kinh khác nhau — và đường xử lý âm thanh không xã hội thường không bị ảnh hưởng theo cùng cách."
          }
        },
        {
          "@type": "Question",
          "name": "Con bao nhiêu tuổi thì bắt đầu can thiệp?",
          "acceptedAnswer": {
            "@type": "Answer",
            "text": "Càng sớm càng tốt. Nghiên cứu nhất quán chỉ ra rằng can thiệp bắt đầu trước 3 tuổi cho kết quả tốt hơn đáng kể. Tuy nhiên, can thiệp ở bất kỳ độ tuổi nào cũng đều có giá trị — não bộ con người có khả năng thích nghi (neuroplasticity) đáng kể."
          }
        },
        {
          "@type": "Question",
          "name": "Nếu con phản ứng tên ở nhà nhưng không phản ứng ở nơi khác?",
          "acceptedAnswer": {
            "@type": "Answer",
            "text": "Đây là hiện tượng rất phổ biến gọi là \"khó khái quát hóa\" (generalization deficit). Con đã học được phản xạ trong bối cảnh quen thuộc, nhưng chưa chuyển được kỹ năng đó sang môi trường mới. Đây là lý do tại sao các chương trình can thiệp chú trọng đến việc luyện tập trong nhiều bối cảnh, nhiều người khác nhau."
          }
        },
        {
          "@type": "Question",
          "name": "Việc luyện tập gọi tên ở nhà có ích không nếu chưa có chuyên gia?",
          "acceptedAnswer": {
            "@type": "Answer",
            "text": "Có, và rất quan trọng — nhưng cần làm đúng cách. Gọi tên quá nhiều mà không có phản ứng dương tính khi con quay lại có thể làm tên trở thành âm thanh \"nền\" vô nghĩa. Nguyên tắc: gọi ít hơn nhưng mỗi lần có phản ứng của con (dù nhỏ) đều được nhận ra và khen ngay."
          }
        },
        {
          "@type": "Question",
          "name": "Trẻ bao lâu thì bắt đầu phản ứng tên sau khi được can thiệp?",
          "acceptedAnswer": {
            "@type": "Answer",
            "text": "Thời gian thay đổi đáng kể tùy theo mức độ khó khăn và cường độ luyện tập. Một số trẻ phản ứng cải thiện sau vài tuần luyện tập nhất quán; một số khác cần nhiều tháng. Nghiên cứu cho thấy kết quả tốt nhất khi can thiệp được duy trì đủ cường độ và kéo dài từ 12 tháng trở lên."
          }
        }
      ]
    },
    {
      "@type": "BreadcrumbList",
      "itemListElement": [
        {
          "@type": "ListItem",
          "position": 1,
          "name": "Trang chủ",
          "item": "https://npfood.edu.vn"
        },
        {
          "@type": "ListItem",
          "position": 2,
          "name": "Triệu chứng tự kỷ",
          "item": "https://npfood.edu.vn/trieu-chung-tu-ky/"
        },
        {
          "@type": "ListItem",
          "position": 3,
          "name": "Trẻ Tự Kỷ Không Phản Ứng Khi Gọi Tên: Vì Sao Và Cách Hỗ Trợ",
          "item": "https://npfood.edu.vn/tr-t-k-khong-ph-n-ung-khi-goi-ten-vi-sao"
        }
      ]
    }
  ]
}
</script>
<?php get_footer(); ?>